// frontend-r/src/App.tsx
import React, { Component } from "react";
import { Container } from "reactstrap";
import CSS from "csstype";
import io, { Socket } from "socket.io-client";

import Header from "./components/Header";
import Messages from "./components/Messages";
import MessageBox from "./components/MessageBox";
import LogIn from "./components/LogIn";

import IMessage from "./interfaces/Message.interface";

export default class App extends Component {
  state: Readonly<State> = {
    messages: [],
    name: "",
    socket: io("http://localhost:4000", { autoConnect: false })
  };

  connect = (name: string) => {
    this.state.socket.connect();
    this.state.socket.emit("update name", name);
    this.setState({
      name: name
    })
  }

  componentDidMount = () => {
    this.state.socket.on("new connection", (name: string) => {
      // this.new_connection.name = name;
      // this.new_connection.connection = true;
      // this.new_connection.status = true;
      // setTimeout(() => this.resetNewConnection(), 5000);
      console.log(name)
    });
    this.state.socket.on("new message", (data: IMessage) => {
      this.setState((prevState: State) => ({
        messages: [...prevState.messages, data]
      }))
    });
  }

  render() {
    return (
      <div>
        <Header name={this.state.name} />
        <Container className="mt-3">
          {this.state.name ? (
            <div style={style.div}>
              <Messages messages={this.state.messages} />
              <MessageBox />
            </div>
          ) : (
            <LogIn connectHandler={this.connect}/>
          )}
        </Container>
      </div>
    );
  }
}

interface State {
  messages: IMessage[];
  name: string;
  socket: SocketIOClient.Socket;
}

let style: { [id: string]: CSS.Properties } = {
  div: {
    border: "5px solid #343a40",
    borderRadius: "5px",
    height: "85vh",
    position: "relative",
  },
};

// frontend/src/App.vue
<template>
  <div>
    <Header />
    <div class="container" v-if="connected">
      <!-- <Test /> -->
      <Jumbotron :name="name" />
      <Messages :messages="messages" />
      <div class="input-group mb-3">
        <input type="text" class="form-control" v-model="message" />
        <div class="input-group-append">
          <button
            class="btn btn-outline-secondary"
            type="button"
            @click="sendMessage"
          >
            Send
          </button>
        </div>
      </div>
    </div>
    <div v-else class="container jumbotron mt-4">
      <div class="input-group">
        <input
          type="text"
          class="form-control"
          placeholder="Name"
          v-model="name"
        />
        <div class="input-group-append">
          <button
            class="btn btn-outline-secondary"
            type="button"
            @click="updateName"
          >
            Connect!
          </button>
        </div>
      </div>
    </div>
    <div
      class="toast"
      style="position: absolute; top: 2em; right: 1em;"
      :class="new_connection.status ? 'show' : 'hide'"
    >
      <div class="toast-header">
        <span class="mr-auto">{{
          new_connection.connection ? "New connection" : "Someone leaved"
        }}</span>
        <small>Now</small>
      </div>
      <div class="toast-body">
        <span class="font-weight-bold">{{ new_connection.name }}</span>
        {{ new_connection.connection ? "connected" : "disconnected" }}
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { Options, Vue } from "vue-class-component";
import Header from "./components/Header.vue";
import Jumbotron from './components/Jumbotron.vue'
import Messages from "./components/Messages.vue"
import Test from './components/Test.vue'

import io, { Socket } from "socket.io-client";
import { IncomingMessage } from "./interfaces";

@Options({
  components: {
    Header,
    Jumbotron,
    Messages,
    Test
  },
})
export default class App extends Vue {
  private socket: SocketIOClient.Socket = io({ autoConnect: false });
  private message = "";
  private messages: IncomingMessage[] = [];
  private name = "";
  private connected = false;
  private new_connection = {
    status: false,
    connection: false,
    name: "",
  };

  // created() {}

  public resetNewConnection() {
    this.new_connection.status = false;
  }

  public async updateName() {
    if (!this.name) return;
    this.socket = await io("http://localhost:4000");
    this.socket.emit("update name", this.name);
    if (this.socket) this.connected = true;
    this.socket.on("new message", (data: IncomingMessage) => {
      this.messages.push(data);
    });
    this.socket.on("new connection", (name: string) => {
      this.new_connection.name = name;
      this.new_connection.connection = true;
      this.new_connection.status = true;
      setTimeout(() => this.resetNewConnection(), 5000);
    });
    this.socket.on("someone disconnected", (name: string) => {
      this.new_connection.name = name;
      this.new_connection.connection = false;
      this.new_connection.status = true;
      setTimeout(() => this.resetNewConnection(), 5000);
    });
  }

  public sendMessage() {
    if (this.message === "" || !this.connected) return;
    this.socket.emit("message", this.message);
    this.message = "";
  }
}
</script>

<style lang="scss"></style>
